package pcd.practica_4;

import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class FrameCola extends javax.swing.JFrame {
    
    private static final int ANCHO = 550, ALTO = 600, CAPACIDAD = 10;

    /**
     * Creates new form FrameCola
     */
    public FrameCola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        FrameCola f = new FrameCola();
        ColaCanvas canvas = new ColaCanvas(CAPACIDAD);
        canvas.setSize(ANCHO, ALTO);
        canvas.setBackground(Color.lightGray);
        f.setSize(ANCHO, ALTO);
        f.add(canvas);
        f.setTitle("Adrian Alvarez practica 4 PCD");
        f.setResizable(false);
        f.setLocationRelativeTo(null);
        f.setVisible(true);

        ColaLenta c = new ColaLenta(CAPACIDAD, canvas);

        Thread p1 = new Productor(c);
        Thread p2 = new Productor(c);
        Thread p3 = new Productor(c);
        Thread p4 = new Productor(c);
        Thread c1 = new Thread(new Consumidor(c));

        p1.start();
        p2.start();
        p3.start();
        p4.start();
        c1.start();
        
        c1.join();

        p1.interrupt();
        p2.interrupt();
        p3.interrupt();
        p4.interrupt();
        
        p1.join();
        p2.join();
        p3.join();
        p4.join();
        
        Thread.sleep(5000);
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
